(ns aoc-2025-clojure.day-07-test 
  (:require
   [aoc-2025-clojure.day-07 :refer [part-1 part-2]]
   [clojure.test :refer [deftest is testing]]))

(def input ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............")

(deftest day-07
  (testing "Day 07 - Part 1"
    (is (= 21 (part-1 input))))
  (testing "Day 07 - Part 2"
    (is (= 40 (part-2 input)))))
